# Generated by Django 4.2.3 on 2023-09-02 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndoUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'IndoUsers',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=20)),
                ('ProductDetails', models.TextField()),
                ('ProductPrice', models.FloatField()),
                ('ProductCategory', models.CharField(choices=[('Mobile', 'Mobile'), ('Camera', 'Camera'), ('Neckband', 'Neckband'), ('Tablet', 'Tablet'), ('TV', 'TV'), ('Earphone', 'Earphone'), ('Printer', 'Printer'), ('Headphone', 'Headphone'), ('Watch', 'Watch'), ('CPU', 'CPU'), ('Mouse', 'Mouse'), ('Keyboard', 'Keyboard')], max_length=20)),
                ('ProductImage', models.ImageField(upload_to='Products_images')),
                ('ProductBrand', models.CharField(choices=[('HP', 'HP'), ('DELL', 'DELL'), ('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Realme', 'Realme'), ('Redmi', 'Redmi'), ('LG', 'LG'), ('Sony', 'Sony'), ('Motorola', 'Motorola'), ('Zebronics', 'Zebronics')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunanchal Pradesh', 'Arunanchal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandighar', 'Chandighar'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadar & Nagar Haveli', 'Dadar & Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal', 'Himachal'), ('Jammu & kashmir', 'Jammu & kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharastra', 'Maharastra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttarakhand', 'Uttarakhand'), ('Uttar Pradesh', 'Uttar Pradesh'), ('West Bengal', 'West Bengal')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indoapp2.indousers')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indoapp2.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indoapp2.indousers')),
            ],
        ),
    ]
