# Generated by Django 4.2.3 on 2023-09-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoapp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='user',
            field=models.IntegerField(),
        ),
    ]
