# Generated by Django 4.2.3 on 2023-09-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoapp2', '0003_alter_cart_product_alter_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='KartProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('product', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ProductName', models.CharField(max_length=20)),
                ('ProductDetails', models.TextField()),
                ('ProductPrice', models.FloatField()),
                ('ProductCategory', models.CharField(choices=[('Mobile', 'Mobile'), ('Camera', 'Camera'), ('Neckband', 'Neckband'), ('Tablet', 'Tablet'), ('TV', 'TV'), ('Earphone', 'Earphone'), ('Printer', 'Printer'), ('Headphone', 'Headphone'), ('Watch', 'Watch'), ('CPU', 'CPU'), ('Mouse', 'Mouse'), ('Keyboard', 'Keyboard')], max_length=20)),
                ('ProductImage', models.ImageField(upload_to='Products_images')),
            ],
        ),
    ]
