# Generated by Django 4.2.3 on 2023-09-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoapp2', '0004_kartproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('customer', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50)),
            ],
        ),
    ]
