# Generated by Django 4.2.3 on 2023-09-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoapp2', '0005_orderplaced'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('customer', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ProductName', models.CharField(max_length=20)),
                ('ProductDetails', models.TextField()),
                ('ProductPrice', models.FloatField()),
                ('ProductCategory', models.CharField(choices=[('Mobile', 'Mobile'), ('Camera', 'Camera'), ('Neckband', 'Neckband'), ('Tablet', 'Tablet'), ('TV', 'TV'), ('Earphone', 'Earphone'), ('Printer', 'Printer'), ('Headphone', 'Headphone'), ('Watch', 'Watch'), ('CPU', 'CPU'), ('Mouse', 'Mouse'), ('Keyboard', 'Keyboard')], max_length=20)),
                ('ProductImage', models.ImageField(upload_to='Products_images')),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50)),
            ],
        ),
    ]
