# Generated by Django 4.2.3 on 2023-07-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=20)),
                ('ProductDetails', models.TextField()),
                ('ProductPrice', models.FloatField()),
                ('ProductCategory', models.CharField(choices=[('Mobile', 'Mobile'), ('Camera', 'Camera'), ('Neckband', 'Neckband'), ('Tablet', 'Tablet'), ('TV', 'TV'), ('Earphone', 'Earphone'), ('Printer', 'Printer'), ('Headphone', 'Headphone'), ('Watch', 'Watch'), ('CPU', 'CPU'), ('Mouse', 'Mouse'), ('Keyboard', 'Keyboard')], max_length=20)),
                ('ProductImage', models.ImageField(upload_to='')),
                ('ProductBrand', models.CharField(choices=[('HP', 'HP'), ('DELL', 'DELL'), ('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Realme', 'Realme'), ('Redmi', 'Redmi'), ('LG', 'LG'), ('Sony', 'Sony'), ('Motorola', 'Motorola'), ('Zebronics', 'Zebronics')], max_length=20)),
            ],
        ),
    ]
